### ISSUE TITLE
Uncaught exception TypeError in urlopen

### ISSUE THREAD

**Issue by seanodea** [TextRazor/textrazor-python#13]
TypeError: expected string or bytes-like object happens when you don't give cleanup options as "True" instead of True.

**Comment by seanodea** [comment]
Actually that's not the problem. I cannot figure out the issue. Here is the traceback, I'm just plugging a string URL in. I'm using wsl ubuntu 18.04.

Traceback (most recent call last):
  File "/home/cgodwin/gcode/cporg-nlp/./oghma", line 331, in <module>
    retval.append(processThisShit(site, yaml_body['sites'][site]))
  File "/home/cgodwin/gcode/cporg-nlp/./oghma", line 43, in processThisShit
    topics = processTopics(site_links, site_yaml)
  File "/home/cgodwin/gcode/cporg-nlp/./oghma", line 250, in processTopics
    try: response = client.analyze_url(url) #text_content)
  File "/home/cgodwin/.local/lib/python3.9/site-packages/textrazor.py", line 1588, in analyze_url
    return TextRazorResponse(self.do_request("", urlencode(post_data), method="POST"))
  File "/home/cgodwin/.local/lib/python3.9/site-packages/textrazor.py", line 208, in do_request
    response = urlopen(request)
  File "/usr/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1346, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.9/http/client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.9/http/client.py", line 1294, in _send_request
    self.putheader(hdr, value)
  File "/usr/lib/python3.9/http/client.py", line 1230, in putheader
    if _is_illegal_header_value(values[i]):
TypeError: expected string or bytes-like object

**Comment by crayston** [comment]
Hi @seanodea, it looks like the problem is in one of the headers being sent with the request, which is most likely the textrazor.api_key field. Could you check that is being set correctly? If you still have no luck, please send us a sample of your code to support@textrazor.com and we'd be happy to dig into this further.

**Comment by seanodea** [comment]
Well lookie there, os.environ.get returns the api key as a None type. Now stringified, Thanks!
